;generated by save-globals.g
set global.print_start_setup = 0
set global.auto_swap_left = false
set global.auto_swap_right = false
set global.multi_material_mode = false
set global.pause_on_monitor = 0
set global.leveling = 0
set global.mesh = 0
set global.hvc = 0
set global.homeZ = 0
